2020-10-06 16:38:44.918548: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Running tests under Python 3.6.12: C:\ProgramData\Anaconda3\envs\keras\python.exe
[ RUN      ] ControlFlowTest.test_for_composite_state_initialized_in_loop
[  FAILED  ] ControlFlowTest.test_for_composite_state_initialized_in_loop
[ RUN      ] ControlFlowTest.test_for_iterated_expression
[       OK ] ControlFlowTest.test_for_iterated_expression
[ RUN      ] ControlFlowTest.test_for_single_output
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py:60: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
W1006 16:38:49.962051 15280 deprecation.py:323] From C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py:60: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
2020-10-06 16:38:49.978244: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-10-06 16:38:50.096213: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:38:50.096745: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:38:50.100344: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:38:50.103762: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:38:50.105451: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:38:50.110123: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:38:50.113293: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:38:50.123562: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:38:50.124504: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:38:50.125122: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-10-06 16:38:50.139187: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:38:50.139844: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:38:50.140275: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:38:50.140694: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:38:50.141061: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:38:50.141430: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:38:50.141800: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:38:50.142175: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:38:50.143056: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:38:51.078810: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:38:51.079226: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:38:51.079466: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:38:51.080210: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_for_single_output
[ RUN      ] ControlFlowTest.test_for_tuple_unpacking
2020-10-06 16:38:51.632300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:38:51.632840: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:38:51.633185: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:38:51.633540: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:38:51.633889: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:38:51.634239: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:38:51.634585: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:38:51.634943: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:38:51.635504: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:38:51.635814: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:38:51.636166: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:38:51.636386: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:38:51.636869: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_for_tuple_unpacking
[ RUN      ] ControlFlowTest.test_for_with_comprehension_in_body
2020-10-06 16:38:51.680244: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:38:51.680849: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:38:51.681223: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:38:51.681593: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:38:51.681958: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:38:51.682300: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:38:51.682647: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:38:51.682993: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:38:51.683603: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:38:51.683921: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:38:51.684273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:38:51.684495: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:38:51.684978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_for_with_comprehension_in_body
[ RUN      ] ControlFlowTest.test_if_basic
[  FAILED  ] ControlFlowTest.test_if_basic
[ RUN      ] ControlFlowTest.test_if_complex_outputs
[  FAILED  ] ControlFlowTest.test_if_complex_outputs
[ RUN      ] ControlFlowTest.test_if_local_var
[  FAILED  ] ControlFlowTest.test_if_local_var
[ RUN      ] ControlFlowTest.test_if_no_outputs
[  FAILED  ] ControlFlowTest.test_if_no_outputs
[ RUN      ] ControlFlowTest.test_if_semi
[  FAILED  ] ControlFlowTest.test_if_semi
[ RUN      ] ControlFlowTest.test_if_single_output
[  FAILED  ] ControlFlowTest.test_if_single_output
[ RUN      ] ControlFlowTest.test_if_sparse_tensor
[  FAILED  ] ControlFlowTest.test_if_sparse_tensor
[ RUN      ] ControlFlowTest.test_if_unbalanced_composite
[  FAILED  ] ControlFlowTest.test_if_unbalanced_composite
[ RUN      ] ControlFlowTest.test_if_unbalanced_multiple_composites
[  FAILED  ] ControlFlowTest.test_if_unbalanced_multiple_composites
[ RUN      ] ControlFlowTest.test_session
[  SKIPPED ] ControlFlowTest.test_session
[ RUN      ] ControlFlowTest.test_simple_for
2020-10-06 16:38:51.835225: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:38:51.835764: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:38:51.836118: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:38:51.836469: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:38:51.836835: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:38:51.837205: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:38:51.837577: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:38:51.837948: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:38:51.838539: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:38:51.838877: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:38:51.839250: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:38:51.839471: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:38:51.839960: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_simple_for
[ RUN      ] ControlFlowTest.test_while_basic
2020-10-06 16:38:51.933615: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:38:51.934157: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:38:51.934502: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:38:51.934847: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:38:51.935185: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:38:51.935534: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:38:51.935889: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:38:51.936239: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:38:51.936801: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:38:51.937112: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:38:51.937461: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:38:51.937682: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:38:51.938165: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_while_basic
[ RUN      ] ControlFlowTest.test_while_composite_state
2020-10-06 16:38:51.975776: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:38:51.976318: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:38:51.976664: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:38:51.977006: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:38:51.977351: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:38:51.977693: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:38:51.978039: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:38:51.978384: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:38:51.978994: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:38:51.979329: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:38:51.979694: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:38:51.979912: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:38:51.980391: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_while_composite_state
[ RUN      ] ControlFlowTest.test_while_composite_state_initialized_in_loop
[  FAILED  ] ControlFlowTest.test_while_composite_state_initialized_in_loop
[ RUN      ] ControlFlowTest.test_while_dispatches_by_cond_only
2020-10-06 16:38:52.028029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:38:52.028571: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:38:52.028929: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:38:52.029270: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:38:52.029611: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:38:52.029956: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:38:52.030302: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:38:52.030649: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:38:52.031210: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:38:52.031521: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:38:52.031874: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:38:52.032098: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:38:52.032589: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_while_dispatches_by_cond_only
[ RUN      ] ControlFlowTest.test_while_local_composite
2020-10-06 16:38:52.086950: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:38:52.087480: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:38:52.087829: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:38:52.088174: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:38:52.088511: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:38:52.088863: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:38:52.089207: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:38:52.089556: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:38:52.090134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:38:52.090445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:38:52.090793: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:38:52.091012: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:38:52.091494: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_while_local_composite
[ RUN      ] ControlFlowTest.test_while_local_composite_complex_illegal
[       OK ] ControlFlowTest.test_while_local_composite_complex_illegal
[ RUN      ] ControlFlowTest.test_while_local_composite_complex_nestable
2020-10-06 16:38:52.162293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:38:52.162833: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:38:52.163175: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:38:52.163520: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:38:52.163861: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:38:52.164203: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:38:52.164554: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:38:52.164971: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:38:52.165603: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:38:52.165941: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:38:52.166306: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:38:52.166524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:38:52.167006: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_while_local_composite_complex_nestable
[ RUN      ] ControlFlowTest.test_while_nested
2020-10-06 16:38:52.226710: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:38:52.227247: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:38:52.227606: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:38:52.227948: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:38:52.228289: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:38:52.228632: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:38:52.228977: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:38:52.229322: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:38:52.229883: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:38:52.230195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:38:52.230548: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:38:52.230771: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:38:52.231264: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_while_nested
[ RUN      ] ControlFlowTest.test_while_nested_composite_state
[  FAILED  ] ControlFlowTest.test_while_nested_composite_state
[ RUN      ] ControlFlowTest.test_while_single_output
2020-10-06 16:38:52.279804: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-06 16:38:52.280344: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-06 16:38:52.280692: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-06 16:38:52.281038: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-06 16:38:52.281379: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-06 16:38:52.281766: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-06 16:38:52.282138: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-06 16:38:52.282509: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-06 16:38:52.283141: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-06 16:38:52.283529: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-06 16:38:52.283966: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-06 16:38:52.284217: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-06 16:38:52.284702: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ControlFlowTest.test_while_single_output
======================================================================
ERROR: test_for_composite_state_initialized_in_loop (__main__.ControlFlowTest)
ControlFlowTest.test_for_composite_state_initialized_in_loop
----------------------------------------------------------------------
Traceback (most recent call last):
  File "control_flow_test.py", line 860, in test_for_composite_state_initialized_in_loop
    symbols={'TestClass': TestClass})
  File "control_flow_test.py", line 58, in assertTransformedResult
    (constant_op.constant,)) as result:
  File "C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter_testing.py", line 103, in converted
    node = m.transform(node, ctx)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 578, in transform
    node = ControlFlowTransformer(ctx).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 451, in visit_For
    node = self.generic_visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 201, in visit_If
    created_in_body = body_scope.modified & returned_from_cond + defined_in
TypeError: unsupported operand type(s) for +: 'set' and 'frozenset'

======================================================================
ERROR: test_if_basic (__main__.ControlFlowTest)
ControlFlowTest.test_if_basic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "control_flow_test.py", line 464, in test_if_basic
    self.assertTransformedResult(test_fn, constant_op.constant(1), (-1, 0))
  File "control_flow_test.py", line 58, in assertTransformedResult
    (constant_op.constant,)) as result:
  File "C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter_testing.py", line 103, in converted
    node = m.transform(node, ctx)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 578, in transform
    node = ControlFlowTransformer(ctx).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 201, in visit_If
    created_in_body = body_scope.modified & returned_from_cond + defined_in
TypeError: unsupported operand type(s) for +: 'set' and 'frozenset'

======================================================================
ERROR: test_if_complex_outputs (__main__.ControlFlowTest)
ControlFlowTest.test_if_complex_outputs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "control_flow_test.py", line 530, in test_if_complex_outputs
    with self.converted(test_fn, control_flow, {}) as result:
  File "C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter_testing.py", line 103, in converted
    node = m.transform(node, ctx)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 578, in transform
    node = ControlFlowTransformer(ctx).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 201, in visit_If
    created_in_body = body_scope.modified & returned_from_cond + defined_in
TypeError: unsupported operand type(s) for +: 'set' and 'frozenset'

======================================================================
ERROR: test_if_local_var (__main__.ControlFlowTest)
ControlFlowTest.test_if_local_var
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "control_flow_test.py", line 602, in test_if_local_var
    self.assertTransformedResult(test_fn, constant_op.constant(1), 5)
  File "control_flow_test.py", line 58, in assertTransformedResult
    (constant_op.constant,)) as result:
  File "C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter_testing.py", line 103, in converted
    node = m.transform(node, ctx)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 578, in transform
    node = ControlFlowTransformer(ctx).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 201, in visit_If
    created_in_body = body_scope.modified & returned_from_cond + defined_in
TypeError: unsupported operand type(s) for +: 'set' and 'frozenset'

======================================================================
ERROR: test_if_no_outputs (__main__.ControlFlowTest)
ControlFlowTest.test_if_no_outputs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "control_flow_test.py", line 628, in test_if_no_outputs
    self.assertTransformedResult(test_fn, constant_op.constant(1), 1)
  File "control_flow_test.py", line 58, in assertTransformedResult
    (constant_op.constant,)) as result:
  File "C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter_testing.py", line 103, in converted
    node = m.transform(node, ctx)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 578, in transform
    node = ControlFlowTransformer(ctx).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 201, in visit_If
    created_in_body = body_scope.modified & returned_from_cond + defined_in
TypeError: unsupported operand type(s) for +: 'set' and 'frozenset'

======================================================================
ERROR: test_if_semi (__main__.ControlFlowTest)
ControlFlowTest.test_if_semi
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "control_flow_test.py", line 578, in test_if_semi
    self.assertTransformedResult(test_fn, constant_op.constant(2), 3)
  File "control_flow_test.py", line 58, in assertTransformedResult
    (constant_op.constant,)) as result:
  File "C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter_testing.py", line 103, in converted
    node = m.transform(node, ctx)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 578, in transform
    node = ControlFlowTransformer(ctx).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 201, in visit_If
    created_in_body = body_scope.modified & returned_from_cond + defined_in
TypeError: unsupported operand type(s) for +: 'set' and 'frozenset'

======================================================================
ERROR: test_if_single_output (__main__.ControlFlowTest)
ControlFlowTest.test_if_single_output
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "control_flow_test.py", line 558, in test_if_single_output
    self.assertTransformedResult(test_fn, constant_op.constant(1), -1)
  File "control_flow_test.py", line 58, in assertTransformedResult
    (constant_op.constant,)) as result:
  File "C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter_testing.py", line 103, in converted
    node = m.transform(node, ctx)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 578, in transform
    node = ControlFlowTransformer(ctx).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 201, in visit_If
    created_in_body = body_scope.modified & returned_from_cond + defined_in
TypeError: unsupported operand type(s) for +: 'set' and 'frozenset'

======================================================================
ERROR: test_if_sparse_tensor (__main__.ControlFlowTest)
ControlFlowTest.test_if_sparse_tensor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "control_flow_test.py", line 488, in test_if_sparse_tensor
    self.assertTransformedResult(test_fn, (st, constant_op.constant(1)), -1)
  File "control_flow_test.py", line 58, in assertTransformedResult
    (constant_op.constant,)) as result:
  File "C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter_testing.py", line 103, in converted
    node = m.transform(node, ctx)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 578, in transform
    node = ControlFlowTransformer(ctx).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 201, in visit_If
    created_in_body = body_scope.modified & returned_from_cond + defined_in
TypeError: unsupported operand type(s) for +: 'set' and 'frozenset'

======================================================================
ERROR: test_if_unbalanced_composite (__main__.ControlFlowTest)
ControlFlowTest.test_if_unbalanced_composite
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "control_flow_test.py", line 718, in test_if_unbalanced_composite
    (7, 13))
  File "control_flow_test.py", line 58, in assertTransformedResult
    (constant_op.constant,)) as result:
  File "C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter_testing.py", line 103, in converted
    node = m.transform(node, ctx)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 578, in transform
    node = ControlFlowTransformer(ctx).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 201, in visit_If
    created_in_body = body_scope.modified & returned_from_cond + defined_in
TypeError: unsupported operand type(s) for +: 'set' and 'frozenset'

======================================================================
ERROR: test_if_unbalanced_multiple_composites (__main__.ControlFlowTest)
ControlFlowTest.test_if_unbalanced_multiple_composites
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\framework\test_util.py", line 1216, in decorated
    return f(self, *args, **kwargs)
  File "control_flow_test.py", line 674, in test_if_unbalanced_multiple_composites
    (7, 11, 13))
  File "control_flow_test.py", line 58, in assertTransformedResult
    (constant_op.constant,)) as result:
  File "C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter_testing.py", line 103, in converted
    node = m.transform(node, ctx)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 578, in transform
    node = ControlFlowTransformer(ctx).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 201, in visit_If
    created_in_body = body_scope.modified & returned_from_cond + defined_in
TypeError: unsupported operand type(s) for +: 'set' and 'frozenset'

======================================================================
ERROR: test_while_composite_state_initialized_in_loop (__main__.ControlFlowTest)
ControlFlowTest.test_while_composite_state_initialized_in_loop
----------------------------------------------------------------------
Traceback (most recent call last):
  File "control_flow_test.py", line 218, in test_while_composite_state_initialized_in_loop
    symbols={'TestClass': TestClass})
  File "control_flow_test.py", line 58, in assertTransformedResult
    (constant_op.constant,)) as result:
  File "C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter_testing.py", line 103, in converted
    node = m.transform(node, ctx)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 578, in transform
    node = ControlFlowTransformer(ctx).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 367, in visit_While
    node = self.generic_visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 201, in visit_If
    created_in_body = body_scope.modified & returned_from_cond + defined_in
TypeError: unsupported operand type(s) for +: 'set' and 'frozenset'

======================================================================
ERROR: test_while_nested_composite_state (__main__.ControlFlowTest)
ControlFlowTest.test_while_nested_composite_state
----------------------------------------------------------------------
Traceback (most recent call last):
  File "control_flow_test.py", line 266, in test_while_nested_composite_state
    test_fn, constant_op.constant(5), 0, symbols={'TestClass': TestClass})
  File "control_flow_test.py", line 58, in assertTransformedResult
    (constant_op.constant,)) as result:
  File "C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter_testing.py", line 103, in converted
    node = m.transform(node, ctx)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 578, in transform
    node = ControlFlowTransformer(ctx).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 367, in visit_While
    node = self.generic_visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\core\converter.py", line 346, in visit
    return super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\pyct\transformer.py", line 480, in visit
    result = super(Base, self).visit(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\ast.py", line 253, in visit
    return visitor(node)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\autograph\converters\control_flow.py", line 201, in visit_If
    created_in_body = body_scope.modified & returned_from_cond + defined_in
TypeError: unsupported operand type(s) for +: 'set' and 'frozenset'

----------------------------------------------------------------------
Ran 26 tests in 3.515s

FAILED (errors=12, skipped=1)
