2020-10-05 21:21:13.974245: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Running tests under Python 3.6.12: C:\ProgramData\Anaconda3\envs\keras\python.exe
[ RUN      ] AbcTest.testAbstract
[       OK ] AbcTest.testAbstract
[ RUN      ] AbcTest.testConcrete
[       OK ] AbcTest.testConcrete
[ RUN      ] AbcTest.test_session
[  SKIPPED ] AbcTest.test_session
[ RUN      ] FlattenTest.test_attribute_traversal_key
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W1005 21:21:16.572906 13100 deprecation.py:506] From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2020-10-05 21:21:16.600579: W tensorflow/python/util/util.cc:299] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
[       OK ] FlattenTest.test_attribute_traversal_key
[ RUN      ] FlattenTest.test_attributes_to_ignore
[       OK ] FlattenTest.test_attributes_to_ignore
[ RUN      ] FlattenTest.test_flatten0 (<function FlattenTest.<lambda> at 0x000002013EA03730>)
[       OK ] FlattenTest.test_flatten0 (<function FlattenTest.<lambda> at 0x000002013EA03730>)
[ RUN      ] FlattenTest.test_flatten1 (<class 'list'>)
[       OK ] FlattenTest.test_flatten1 (<class 'list'>)
[ RUN      ] FlattenTest.test_flatten2 (<class 'tuple'>)
[       OK ] FlattenTest.test_flatten2 (<class 'tuple'>)
[ RUN      ] FlattenTest.test_flatten3 (<function <lambda> at 0x000002013E9F9EA0>)
[       OK ] FlattenTest.test_flatten3 (<function <lambda> at 0x000002013E9F9EA0>)
[ RUN      ] FlattenTest.test_model_discover_submodule
[       OK ] FlattenTest.test_model_discover_submodule
[ RUN      ] FlattenTest.test_module_discover_layer_variable
[  FAILED  ] FlattenTest.test_module_discover_layer_variable
[ RUN      ] FlattenTest.test_session
[  SKIPPED ] FlattenTest.test_session
[ RUN      ] FlattenTest.test_with_path
[  FAILED  ] FlattenTest.test_with_path
[ RUN      ] ForwardMethodsTest.testEntersNameScope_call
2020-10-05 21:21:16.682541: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-10-05 21:21:16.809959: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:21:16.810491: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:21:16.813955: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:21:16.817341: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:21:16.818931: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:21:16.823988: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:21:16.827176: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:21:16.836663: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:21:16.837959: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:21:16.838619: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-10-05 21:21:16.852901: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:21:16.853455: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:21:16.853825: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:21:16.854202: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:21:16.854570: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:21:16.854953: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:21:16.855326: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:21:16.855672: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:21:16.856518: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:21:17.801890: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-05 21:21:17.802308: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-05 21:21:17.802540: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-05 21:21:17.803300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py:60: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
W1005 21:21:17.822661 13100 deprecation.py:323] From C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py:60: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
2020-10-05 21:21:17.834392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:21:17.834912: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:21:17.835257: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:21:17.835617: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:21:17.835961: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:21:17.836308: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:21:17.836651: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:21:17.837002: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:21:17.837574: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:21:17.837955: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-05 21:21:17.838332: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-05 21:21:17.838577: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-05 21:21:17.839130: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ForwardMethodsTest.testEntersNameScope_call
[ RUN      ] ForwardMethodsTest.testEntersNameScope_concreteFunction
WARNING:tensorflow:Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x000002013EAC3378> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 'NoneType' object has no attribute '_fields'
W1005 21:21:19.181767 13100 ag_logging.py:146] Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x000002013EAC3378> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 'NoneType' object has no attribute '_fields'
2020-10-05 21:21:19.188902: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:21:19.189431: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:21:19.189796: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:21:19.190137: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:21:19.190474: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:21:19.190819: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:21:19.191168: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:21:19.191513: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:21:19.192088: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:21:19.192403: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-05 21:21:19.192756: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-05 21:21:19.192975: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-05 21:21:19.193481: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
WARNING:tensorflow:Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x00000203A0A92BF8> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 'NoneType' object has no attribute '_fields'
W1005 21:21:19.306742 13100 ag_logging.py:146] Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x00000203A0A92BF8> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 'NoneType' object has no attribute '_fields'
[       OK ] ForwardMethodsTest.testEntersNameScope_concreteFunction
[ RUN      ] ForwardMethodsTest.testFunctionType
[       OK ] ForwardMethodsTest.testFunctionType
[ RUN      ] ForwardMethodsTest.test_session
[  SKIPPED ] ForwardMethodsTest.test_session
[ RUN      ] ModuleTrackingTest.test_non_ctor_submodule
[       OK ] ModuleTrackingTest.test_non_ctor_submodule
[ RUN      ] ModuleTrackingTest.test_session
[  SKIPPED ] ModuleTrackingTest.test_session
[ RUN      ] ModuleTrackingTest.test_submodules
[       OK ] ModuleTrackingTest.test_submodules
[ RUN      ] NameScopeTest.test_memoized_in_tf2
[  SKIPPED ] NameScopeTest.test_memoized_in_tf2
[ RUN      ] NameScopeTest.test_not_memoized_in_tf1
[       OK ] NameScopeTest.test_not_memoized_in_tf1
[ RUN      ] NameScopeTest.test_session
[  SKIPPED ] NameScopeTest.test_session
[ RUN      ] TestModuleNaming.test_construct_in_scope
[       OK ] TestModuleNaming.test_construct_in_scope
[ RUN      ] TestModuleNaming.test_ctor_error_closes_name_scope
[       OK ] TestModuleNaming.test_ctor_error_closes_name_scope
[ RUN      ] TestModuleNaming.test_ctor_error_handles_ctor_not_opening_name_scope
[       OK ] TestModuleNaming.test_ctor_error_handles_ctor_not_opening_name_scope
[ RUN      ] TestModuleNaming.test_does_not_evaluate_property_methods
[       OK ] TestModuleNaming.test_does_not_evaluate_property_methods
[ RUN      ] TestModuleNaming.test_enters_name_scope_in_call
[       OK ] TestModuleNaming.test_enters_name_scope_in_call
[ RUN      ] TestModuleNaming.test_enters_name_scope_in_other_method
[       OK ] TestModuleNaming.test_enters_name_scope_in_other_method
[ RUN      ] TestModuleNaming.test_forward_method_closes_name_scope
[       OK ] TestModuleNaming.test_forward_method_closes_name_scope
[ RUN      ] TestModuleNaming.test_get_attr_doesnt_enter_name_scope
[       OK ] TestModuleNaming.test_get_attr_doesnt_enter_name_scope
[ RUN      ] TestModuleNaming.test_get_attribute_doesnt_enter_name_scope
[       OK ] TestModuleNaming.test_get_attribute_doesnt_enter_name_scope
[ RUN      ] TestModuleNaming.test_invalid_name
[       OK ] TestModuleNaming.test_invalid_name
[ RUN      ] TestModuleNaming.test_module_numbering_in_graph
2020-10-05 21:21:19.332752: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:21:19.333280: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:21:19.333621: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:21:19.333961: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:21:19.334298: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:21:19.334636: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:21:19.334980: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:21:19.335346: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:21:19.335925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:21:19.336231: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-05 21:21:19.336585: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-05 21:21:19.336871: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-05 21:21:19.337394: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  SKIPPED ] TestModuleNaming.test_module_numbering_in_graph
[ RUN      ] TestModuleNaming.test_modules_not_numbered_in_eager
2020-10-05 21:21:19.350017: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:21:19.350536: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:21:19.350895: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:21:19.351243: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:21:19.351580: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:21:19.351926: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:21:19.352270: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:21:19.352613: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:21:19.353177: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:21:19.353489: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-05 21:21:19.353890: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-05 21:21:19.354166: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-05 21:21:19.354763: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] TestModuleNaming.test_modules_not_numbered_in_eager
[ RUN      ] TestModuleNaming.test_overridden_name_scope
[       OK ] TestModuleNaming.test_overridden_name_scope
[ RUN      ] TestModuleNaming.test_patched_callable
[       OK ] TestModuleNaming.test_patched_callable
[ RUN      ] TestModuleNaming.test_property
[       OK ] TestModuleNaming.test_property
[ RUN      ] TestModuleNaming.test_property_no_name_scope
[       OK ] TestModuleNaming.test_property_no_name_scope
[ RUN      ] TestModuleNaming.test_session
[  SKIPPED ] TestModuleNaming.test_session
[ RUN      ] TestModuleNaming.test_single_name
[       OK ] TestModuleNaming.test_single_name
[ RUN      ] TestModuleNaming.test_subclassed_module
[       OK ] TestModuleNaming.test_subclassed_module
[ RUN      ] TestModuleNaming.test_submodule_created_late
[       OK ] TestModuleNaming.test_submodule_created_late
[ RUN      ] VariableNamingTest.test_session
[  SKIPPED ] VariableNamingTest.test_session
[ RUN      ] VariableNamingTest.test_variable_names
[       OK ] VariableNamingTest.test_variable_names
[ RUN      ] VariableTrackingTest.test_session
[  SKIPPED ] VariableTrackingTest.test_session
[ RUN      ] VariableTrackingTest.test_supports_distributed_variables
[       OK ] VariableTrackingTest.test_supports_distributed_variables
[ RUN      ] VariableTrackingTest.test_trainable_variables
[       OK ] VariableTrackingTest.test_trainable_variables
[ RUN      ] VariableTrackingTest.test_trainable_variables_ignores_non_trainable
[       OK ] VariableTrackingTest.test_trainable_variables_ignores_non_trainable
[ RUN      ] VariableTrackingTest.test_variables
[       OK ] VariableTrackingTest.test_variables
======================================================================
FAIL: test_module_discover_layer_variable (__main__.FlattenTest)
FlattenTest.test_module_discover_layer_variable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "module_test.py", line 1052, in test_module_discover_layer_variable
    self.assertLen(variable_list, 4)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\absl\testing\absltest.py", line 926, in assertLen
    container_repr, len(container), expected_len), msg)
  File "C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\absl\testing\absltest.py", line 1764, in fail
    return super(TestCase, self).fail(self._formatMessage(prefix, msg))
AssertionError: (<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32>, <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32>, <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32>, <tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32>, <tf.Variable 'dense_1/kernel:0' shape=(1, 2) dtype=float32>, <tf.Variable 'dense_1/bias:0' shape=(2,) dtype=float32>, <tf.Variable 'dense_1/bias:0' shape=(2,) dtype=float32>, <tf.Variable 'dense_1/kernel:0' shape=(1, 2) dtype=float32>) has length of 8, expected 4.

======================================================================
FAIL: test_with_path (__main__.FlattenTest)
FlattenTest.test_with_path
----------------------------------------------------------------------
Traceback (most recent call last):
  File "module_test.py", line 1020, in test_with_path
    ("decoder", "w", 0, 1, "k"): mod.decoder.w[0][1]["k"]},)
AssertionError: {('w',): <tf.Variable 'Variable:0' shape=() dtype=float32>} != {('decoder', 'w', 0, 0, 'k'): <tf.Variable 'Variable:0' shape=() dtype=float32>, ('decoder', 'w', 0, 1, 'k'): <tf.Variable 'Variable:0' shape=() dtype=float32>, ('encoder', 'w', 0, 0, 'k'): <tf.Variable 'Variable:0' shape=() dtype=float32>, ('encoder', 'w', 0, 1, 'k'): <tf.Variable 'Variable:0' shape=() dtype=float32>, ('w',): <tf.Variable 'Variable:0' shape=() dtype=float32>}
Unexpected, but present entries:
('decoder', 'w', 0, 0, 'k'): <tf.Variable 'Variable:0' shape=() dtype=float32>
('decoder', 'w', 0, 1, 'k'): <tf.Variable 'Variable:0' shape=() dtype=float32>
('encoder', 'w', 0, 0, 'k'): <tf.Variable 'Variable:0' shape=() dtype=float32>
('encoder', 'w', 0, 1, 'k'): <tf.Variable 'Variable:0' shape=() dtype=float32>


----------------------------------------------------------------------
Ran 50 tests in 2.859s

FAILED (failures=2, skipped=10)
