2020-10-05 21:19:54.695747: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Running tests under Python 3.6.12: C:\ProgramData\Anaconda3\envs\keras\python.exe
[ RUN      ] AbcTest.testAbstract
[       OK ] AbcTest.testAbstract
[ RUN      ] AbcTest.testConcrete
[       OK ] AbcTest.testConcrete
[ RUN      ] AbcTest.test_session
[  SKIPPED ] AbcTest.test_session
[ RUN      ] FlattenTest.test_attribute_traversal_key
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W1005 21:19:57.301966 11820 deprecation.py:506] From C:\ProgramData\Anaconda3\envs\keras\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2020-10-05 21:19:57.327815: W tensorflow/python/util/util.cc:299] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
[       OK ] FlattenTest.test_attribute_traversal_key
[ RUN      ] FlattenTest.test_attributes_to_ignore
[       OK ] FlattenTest.test_attributes_to_ignore
[ RUN      ] FlattenTest.test_flatten0 (<function FlattenTest.<lambda> at 0x000001553ADE3730>)
[       OK ] FlattenTest.test_flatten0 (<function FlattenTest.<lambda> at 0x000001553ADE3730>)
[ RUN      ] FlattenTest.test_flatten1 (<class 'list'>)
[       OK ] FlattenTest.test_flatten1 (<class 'list'>)
[ RUN      ] FlattenTest.test_flatten2 (<class 'tuple'>)
[       OK ] FlattenTest.test_flatten2 (<class 'tuple'>)
[ RUN      ] FlattenTest.test_flatten3 (<function <lambda> at 0x000001553ADD8EA0>)
[       OK ] FlattenTest.test_flatten3 (<function <lambda> at 0x000001553ADD8EA0>)
[ RUN      ] FlattenTest.test_model_discover_submodule
[       OK ] FlattenTest.test_model_discover_submodule
[ RUN      ] FlattenTest.test_module_discover_layer_variable
[       OK ] FlattenTest.test_module_discover_layer_variable
[ RUN      ] FlattenTest.test_session
[  SKIPPED ] FlattenTest.test_session
[ RUN      ] FlattenTest.test_with_path
[       OK ] FlattenTest.test_with_path
[ RUN      ] ForwardMethodsTest.testEntersNameScope_call
2020-10-05 21:19:57.407647: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-10-05 21:19:57.536925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:19:57.537617: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:19:57.542574: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:19:57.547184: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:19:57.549003: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:19:57.555406: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:19:57.559657: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:19:57.572229: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:19:57.573205: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:19:57.573844: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-10-05 21:19:57.589046: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:19:57.589610: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:19:57.589956: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:19:57.590299: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:19:57.590634: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:19:57.590972: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:19:57.591314: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:19:57.591655: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:19:57.592507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:19:58.674397: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-05 21:19:58.674787: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-05 21:19:58.675008: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-05 21:19:58.675804: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py:60: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
W1005 21:19:58.692323 11820 deprecation.py:323] From C:\ProgramData\Anaconda3\envs\keras\lib\contextlib.py:60: TensorFlowTestCase.test_session (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `self.session()` or `self.cached_session()` instead.
2020-10-05 21:19:58.706462: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:19:58.706982: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:19:58.707323: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:19:58.707677: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:19:58.708042: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:19:58.708408: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:19:58.708781: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:19:58.709155: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:19:58.709724: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:19:58.710095: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-05 21:19:58.710448: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-05 21:19:58.710670: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-05 21:19:58.711195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] ForwardMethodsTest.testEntersNameScope_call
[ RUN      ] ForwardMethodsTest.testEntersNameScope_concreteFunction
WARNING:tensorflow:Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x000001553AE01E18> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 'NoneType' object has no attribute '_fields'
W1005 21:20:00.051424 11820 ag_logging.py:146] Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x000001553AE01E18> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 'NoneType' object has no attribute '_fields'
2020-10-05 21:20:00.065401: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:20:00.065926: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:20:00.066267: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:20:00.066610: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:20:00.066945: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:20:00.067402: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:20:00.067851: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:20:00.068293: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:20:00.068871: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:20:00.069178: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-05 21:20:00.069529: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-05 21:20:00.069750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-05 21:20:00.070256: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
WARNING:tensorflow:Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x00000157A0DF79D8> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 'NoneType' object has no attribute '_fields'
W1005 21:20:00.176399 11820 ag_logging.py:146] Entity <function Function._initialize_uninitialized_variables.<locals>.initialize_variables at 0x00000157A0DF79D8> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: 'NoneType' object has no attribute '_fields'
[       OK ] ForwardMethodsTest.testEntersNameScope_concreteFunction
[ RUN      ] ForwardMethodsTest.testFunctionType
[       OK ] ForwardMethodsTest.testFunctionType
[ RUN      ] ForwardMethodsTest.test_session
[  SKIPPED ] ForwardMethodsTest.test_session
[ RUN      ] ModuleTrackingTest.test_non_ctor_submodule
[       OK ] ModuleTrackingTest.test_non_ctor_submodule
[ RUN      ] ModuleTrackingTest.test_session
[  SKIPPED ] ModuleTrackingTest.test_session
[ RUN      ] ModuleTrackingTest.test_submodules
[       OK ] ModuleTrackingTest.test_submodules
[ RUN      ] NameScopeTest.test_memoized_in_tf2
[  SKIPPED ] NameScopeTest.test_memoized_in_tf2
[ RUN      ] NameScopeTest.test_not_memoized_in_tf1
[       OK ] NameScopeTest.test_not_memoized_in_tf1
[ RUN      ] NameScopeTest.test_session
[  SKIPPED ] NameScopeTest.test_session
[ RUN      ] TestModuleNaming.test_construct_in_scope
[       OK ] TestModuleNaming.test_construct_in_scope
[ RUN      ] TestModuleNaming.test_ctor_error_closes_name_scope
[       OK ] TestModuleNaming.test_ctor_error_closes_name_scope
[ RUN      ] TestModuleNaming.test_ctor_error_handles_ctor_not_opening_name_scope
[       OK ] TestModuleNaming.test_ctor_error_handles_ctor_not_opening_name_scope
[ RUN      ] TestModuleNaming.test_does_not_evaluate_property_methods
[       OK ] TestModuleNaming.test_does_not_evaluate_property_methods
[ RUN      ] TestModuleNaming.test_enters_name_scope_in_call
[       OK ] TestModuleNaming.test_enters_name_scope_in_call
[ RUN      ] TestModuleNaming.test_enters_name_scope_in_other_method
[       OK ] TestModuleNaming.test_enters_name_scope_in_other_method
[ RUN      ] TestModuleNaming.test_forward_method_closes_name_scope
[       OK ] TestModuleNaming.test_forward_method_closes_name_scope
[ RUN      ] TestModuleNaming.test_get_attr_doesnt_enter_name_scope
[       OK ] TestModuleNaming.test_get_attr_doesnt_enter_name_scope
[ RUN      ] TestModuleNaming.test_get_attribute_doesnt_enter_name_scope
[       OK ] TestModuleNaming.test_get_attribute_doesnt_enter_name_scope
[ RUN      ] TestModuleNaming.test_invalid_name
[       OK ] TestModuleNaming.test_invalid_name
[ RUN      ] TestModuleNaming.test_module_numbering_in_graph
2020-10-05 21:20:00.233752: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:20:00.234485: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:20:00.234972: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:20:00.235456: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:20:00.235934: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:20:00.236416: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:20:00.236905: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:20:00.237412: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:20:00.238201: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:20:00.238632: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-05 21:20:00.239106: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-05 21:20:00.239449: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-05 21:20:00.240090: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[  SKIPPED ] TestModuleNaming.test_module_numbering_in_graph
[ RUN      ] TestModuleNaming.test_modules_not_numbered_in_eager
2020-10-05 21:20:00.252906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.65
pciBusID: 0000:73:00.0
2020-10-05 21:20:00.253421: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-10-05 21:20:00.253796: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-10-05 21:20:00.254173: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-10-05 21:20:00.254589: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-10-05 21:20:00.255026: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-10-05 21:20:00.255393: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-10-05 21:20:00.255762: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-10-05 21:20:00.256331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-10-05 21:20:00.256634: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-05 21:20:00.256997: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-10-05 21:20:00.257227: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-10-05 21:20:00.257752: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8686 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:73:00.0, compute capability: 7.5)
[       OK ] TestModuleNaming.test_modules_not_numbered_in_eager
[ RUN      ] TestModuleNaming.test_overridden_name_scope
[       OK ] TestModuleNaming.test_overridden_name_scope
[ RUN      ] TestModuleNaming.test_patched_callable
[       OK ] TestModuleNaming.test_patched_callable
[ RUN      ] TestModuleNaming.test_property
[       OK ] TestModuleNaming.test_property
[ RUN      ] TestModuleNaming.test_property_no_name_scope
[       OK ] TestModuleNaming.test_property_no_name_scope
[ RUN      ] TestModuleNaming.test_session
[  SKIPPED ] TestModuleNaming.test_session
[ RUN      ] TestModuleNaming.test_single_name
[       OK ] TestModuleNaming.test_single_name
[ RUN      ] TestModuleNaming.test_subclassed_module
[       OK ] TestModuleNaming.test_subclassed_module
[ RUN      ] TestModuleNaming.test_submodule_created_late
[       OK ] TestModuleNaming.test_submodule_created_late
[ RUN      ] VariableNamingTest.test_session
[  SKIPPED ] VariableNamingTest.test_session
[ RUN      ] VariableNamingTest.test_variable_names
[       OK ] VariableNamingTest.test_variable_names
[ RUN      ] VariableTrackingTest.test_session
[  SKIPPED ] VariableTrackingTest.test_session
[ RUN      ] VariableTrackingTest.test_supports_distributed_variables
[       OK ] VariableTrackingTest.test_supports_distributed_variables
[ RUN      ] VariableTrackingTest.test_trainable_variables
[       OK ] VariableTrackingTest.test_trainable_variables
[ RUN      ] VariableTrackingTest.test_trainable_variables_ignores_non_trainable
[  FAILED  ] VariableTrackingTest.test_trainable_variables_ignores_non_trainable
[ RUN      ] VariableTrackingTest.test_variables
[       OK ] VariableTrackingTest.test_variables
======================================================================
FAIL: test_trainable_variables_ignores_non_trainable (__main__.VariableTrackingTest)
VariableTrackingTest.test_trainable_variables_ignores_non_trainable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "module_test.py", line 490, in test_trainable_variables_ignores_non_trainable
    self.assertEqual(len(m.trainable_variables), 0)
AssertionError: 3 != 0

----------------------------------------------------------------------
Ran 50 tests in 3.031s

FAILED (failures=1, skipped=10)
